### ISSUE TITLE
Unable to locate Roblox instillation directory

### ISSUE THREAD

**Issue by TheRoon** [icrann/Rolo#1]
![image](https://user-images.githubusercontent.com/43406961/226417577-16446071-f303-4746-9437-66221772bf8e.png)

Hi I keep getting this issue, any ideas on how to fix it?

Thank you

**Comment by icrann** [comment]
This is because Roblox has been installed somewhere on your device other than the default location. The default location is `C:\Users\username\AppData\Local\Roblox`. This is where Rolo looks for the Roblox files.

If you want you could edit the code in the [GetLatestRobloxPath](https://github.com/crannm/Rolo/blob/main/Rolo/Rolo/Form1.cs) function.

Maybe I will look into adding support for other installation directories in the future.
Thanks for brining this to my attention.

**Comment by TheRoon** [comment]
![image](https://user-images.githubusercontent.com/43406961/226668652-f28241a4-c4ae-4911-ab37-e461e7aef4f5.png)
Roblox is in that location. The image attached is in the C drive.

Please advise, thank you

**Comment by icrann** [comment]
Ok, thats strange, can you please send me a screenshot of what you see inside the Versions folder.

**Comment by icrann** [comment]
Sorry for the super long wait, but in the latest release of Rolo 2.0 you can now customise your Roblox Installation Directory.

**Comment by icrann** [comment]
> ![image](https://user-images.githubusercontent.com/43406961/226668652-f28241a4-c4ae-4911-ab37-e461e7aef4f5.png)
> Roblox is in that location. The image attached is in the C drive.
> 
> Please advise, thank you

Hi,
I was just checking up. Was your issue resolved after the new update? If not I can reopen this issue and look into the bug.
Thanks
